//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halls
    {
        public int HallId { get; set; }
        public string Name { get; set; }
        public int RowsCount { get; set; }
        public int ColsCount { get; set; }
        public string Classification { get; set; }
    }
}
