//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public System.DateTime StartDate { get; set; }
        public string AgeRating { get; set; }
        public string CoverPath { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
