//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int SessionId { get; set; }
        public int MovieId { get; set; }
        public int HallId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public decimal Price { get; set; }
    }
}
